### ISSUE TITLE
[Bug Report] AttributeError: 'FieldInfo' object has no attribute 'required'

### ISSUE THREAD

**Issue by milank94** [tenstorrent/tt-topology#17]
Hitting a `AttributeError: 'FieldInfo' object has no attribute 'required'` on `main`.

Had to revert to `e3cffd18f86c6ec13f1638561ecda81eda8e18ea` to work.

```bash
Traceback (most recent call last):
  File "/home/ttuser/tt-topology/.venv/bin/tt-topology", line 5, in <module>
    from tt_topology import main
  File "/home/ttuser/tt-topology/.venv/lib/python3.8/site-packages/tt_topology/__init__.py", line 7, in <module>
    from .tt_topology import *
  File "/home/ttuser/tt-topology/.venv/lib/python3.8/site-packages/tt_topology/tt_topology.py", line 22, in <module>
    from tt_tools_common.reset_common.reset_utils import (
  File "/home/ttuser/tt-topology/.venv/lib/python3.8/site-packages/tt_tools_common/reset_common/reset_utils.py", line 13, in <module>
    import tt_tools_common.reset_common.host_reset_log as log
  File "/home/ttuser/tt-topology/.venv/lib/python3.8/site-packages/tt_tools_common/reset_common/host_reset_log.py", line 145, in <module>
    class PciResetDeviceInfo(ElasticModel):
  File "/home/ttuser/tt-topology/.venv/lib/python3.8/site-packages/tt_tools_common/reset_common/host_reset_log.py", line 57, in optional
    return dec(cls)
  File "/home/ttuser/tt-topology/.venv/lib/python3.8/site-packages/tt_tools_common/reset_common/host_reset_log.py", line 50, in dec
    _cls.__fields__[field].required = False
AttributeError: 'FieldInfo' object has no attribute 'required'
```

## Steps to reproduce

```bash
git clone https://github.com/tenstorrent/tt-topology.git
cd tt-topology
python3 -m venv .venv
source .venv/bin/activate
pip install -U pip
pip install .
tt-topology -l mesh
```

**Comment by afaerber** [comment]
Sorry to hear that. Could you try bumping the `tt_tools_common` dependency to 1.4.6 or something?
I don't see any other pydantic use inside tt-topology that I could've missed to update to `.v1` imports.

**Comment by tstescoTT** [comment]
I had the same issue, bumping `tt_tools_common` to 1.4.6 fixed this for me.

**Comment by milank94** [comment]
Can we get that fix in main?
